# Generated by Django 5.1.3 on 2024-12-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0001_initial'),
        ('Products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_cart', to='Products_app.products'),
        ),
    ]
