# Generated by Django 5.1.3 on 2025-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0002_alter_ordereditems_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='prize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_product_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
