# Generated by Django 5.1.3 on 2025-01-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0005_rename_prize_ordereditems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_product_price',
        ),
    ]
