# Generated by Django 5.1.3 on 2025-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
